### ISSUE TITLE
Ability to run builds on k8s cloud containers as non root user

### ISSUE THREAD

**Issue by gilShin** [odavid/my-bloody-jenkins#173]
We want to have the ability to run our builds on k8s cloud docker containers as user Jenkins.
In the Jenkins cloud configuration there are these two parameters:
https://ibb.co/kM4F2j6

I assume that these parameters are for changing the default user being used during the build. Am I wrong?

The images that we are using are a base of: ubuntu:xenial and on top of that we are installing our stuff.

Thanks

**Comment by odavid** [comment]
Hi @gilShin - Basically, in order to use the right UID/GID, you will need your agent docker image to support it.
If you take a look [at this image](https://github.com/odavid/jenkins-jnlp-slave), you will find that it is using the UID/GID 1000 username: `jenkins`
The way it is able to use the jenkins user instead of root, is by having the jenkins user be part of the docker group...

In order to achieve that, the image starts with root, but does `exec gosu jenkins $@` - [here](https://github.com/odavid/jenkins-jnlp-slave/blob/master/entrypoint.sh#L42)

The image is able to build docker in 2 ways:
* Mount /var/run/docker.sock and use the docker host on the node.
* Use DinD (I prefer running it that way)
In both ways, the jenkins user is the one who runs the build...

**Comment by gilShin** [comment]
Hi @odavid,

I understand that and our image does have user jenkins as 1000:1000 uid:gid

What I still do not understand is how can I force the build to run as user jenkins without the runAsUser and runAsGroup parameters? I want to supply them the value of 1000 but you currently do not have it in the code.

**Comment by odavid** [comment]
@gilShin - I believe this is what u needed...

**Comment by gilShin** [comment]
Indeed. 

Thanks!
